version: '3.8'

services:
  qc-snapshot-service:
    build: .
    container_name: qc-snapshot-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
    restart: unless-stopped